FROM node:20.10.0

# Instarl required package
RUN apt-get update -y && \
    apt-get install -y curl && \
    apt-get install -y nano

# Create folder to access local file
RUN mkdir /app
WORKDIR /app

CMD tail -f /dev/null
