FROM ubuntu:18.04

# Instarl required package
RUN apt-get update -y && \
    apt-get install -y curl && \
    apt-get install -y nodejs && \
    apt-get install -y npm && \
    apt-get install -y nano

# Create folder to access local file
RUN mkdir /app
WORKDIR /app

CMD tail -f /dev/null
