version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    container_name: gpt-mahjong-app
    volumes:
      - ./app:/app/
    ports:
      - "8080:8080"
